// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace csharp_assmnt_mono.views {
	
	
	public partial class register {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvname;
		
		protected System.Web.UI.WebControls.TextBox TxtEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvemail;
		
		protected System.Web.UI.WebControls.TextBox txtPWD;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPWD;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
	}
}
